# Generated by Django 2.2.27 on 2023-03-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='接口名称', max_length=255, verbose_name='接口名称')),
                ('url', models.URLField(help_text='URL', verbose_name='URL')),
                ('protocol', models.IntegerField(choices=[(1, 'http'), (2, 'https')], help_text='请求协议', verbose_name='请求协议')),
                ('method', models.CharField(help_text='请求方法', max_length=20, verbose_name='请求方法')),
                ('input_data', models.TextField(help_text='请求数据', verbose_name='请求数据')),
                ('headers', models.TextField(help_text='请求头', verbose_name='请求头')),
            ],
            options={
                'verbose_name': '接口',
                'verbose_name_plural': '接口',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='项目名称', max_length=255, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, help_text='描述', verbose_name='描述')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('case_id', models.IntegerField(help_text='关联的测试用例ID', verbose_name='用例ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='测试执行开始时间', verbose_name='开始时间')),
                ('end_time', models.DateTimeField(auto_now=True, help_text='测试执行结束时间', verbose_name='结束时间')),
                ('result', models.BooleanField(help_text='测试用例执行结果，True表示通过，False表示失败', verbose_name='测试结果')),
                ('response_content', models.TextField(blank=True, help_text='接口返回的响应内容', verbose_name='响应内容')),
                ('response_code', models.IntegerField(blank=True, help_text='接口返回的响应状态码', null=True, verbose_name='响应状态码')),
                ('response_headers', models.TextField(blank=True, help_text='接口返回的响应头', verbose_name='响应头')),
                ('duration', models.FloatField(help_text='测试用例执行所花费的时间', verbose_name='执行时长')),
            ],
            options={
                'verbose_name': '用例结果',
                'verbose_name_plural': '用例结果',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('username', models.CharField(help_text='系统用户的登录用户名', max_length=255, unique=True, verbose_name='用户名')),
                ('password', models.CharField(help_text='系统用户的登录密码', max_length=255, verbose_name='密码')),
                ('email', models.EmailField(help_text='系统用户的电子邮箱', max_length=254, unique=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '系统用户',
                'verbose_name_plural': '系统用户',
            },
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='用例名称', max_length=25, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, help_text='用例描述', verbose_name='用例描述')),
                ('input_data', models.TextField(help_text='输入数据', verbose_name='输入数据')),
                ('interface', models.ForeignKey(help_text='断言', on_delete=django.db.models.deletion.CASCADE, to='api.Interface', verbose_name='断言')),
                ('project', models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='api.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '用例',
                'verbose_name_plural': '用例',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('project', models.ForeignKey(help_text='参与的项目', on_delete=django.db.models.deletion.CASCADE, to='api.Project', verbose_name='项目')),
                ('user', models.ForeignKey(help_text='参与项目的系统用户', on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
            },
        ),
        migrations.AddField(
            model_name='interface',
            name='project',
            field=models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='api.Project', verbose_name='所属项目'),
        ),
        migrations.CreateModel(
            name='environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='环境名称', max_length=20, verbose_name='环境名称')),
                ('input_data', models.TextField(help_text='输入数据', verbose_name='输入数据')),
                ('headers', models.TextField(help_text='请求头', verbose_name='请求头')),
                ('project', models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='api.Project', verbose_name='所属项目')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assertion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('assertion_type', models.CharField(help_text='断言方式：eq：equals、in：in、re：正则匹配、lt：less than、gt：greater thanschema: schema mach', max_length=20, verbose_name='断言方式')),
                ('expected_value', models.TextField(help_text='断言预期值', verbose_name='预期值')),
                ('actual_value', models.TextField(help_text='响应实际值表达式', verbose_name='实际值')),
                ('testcase', models.ForeignKey(help_text='所属用例id', on_delete=django.db.models.deletion.CASCADE, to='api.Testcase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '断言',
                'verbose_name_plural': '断言',
            },
        ),
    ]
