# Generated by Django 4.1.7 on 2023-08-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assertion',
            name='actual_value',
        ),
        migrations.RemoveField(
            model_name='assertion',
            name='expected_value',
        ),
        migrations.AddField(
            model_name='assertion',
            name='expression',
            field=models.TextField(default=None, help_text='断言表达式', verbose_name='断言表达式'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assertion',
            name='assertion_type',
            field=models.CharField(help_text='断言方式：json、re：正则匹配、schema: schema mach', max_length=20, verbose_name='断言方式'),
        ),
    ]
