# Generated by Django 2.2.27 on 2023-03-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environment',
            options={'verbose_name': '环境变量', 'verbose_name_plural': '环境变量'},
        ),
        migrations.RemoveField(
            model_name='interface',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='project',
        ),
        migrations.AddField(
            model_name='environment',
            name='base_url',
            field=models.TextField(default='', help_text='请求域名', verbose_name='请求域名'),
        ),
        migrations.AddField(
            model_name='interface',
            name='form_data',
            field=models.TextField(blank=True, help_text='key1,value1;key2,value2;', verbose_name='from表单数据'),
        ),
        migrations.AddField(
            model_name='interface',
            name='json_data',
            field=models.TextField(blank=True, help_text='key1,value1;key2,value2;', verbose_name='json请求数据'),
        ),
        migrations.AddField(
            model_name='interface',
            name='query_data',
            field=models.TextField(blank=True, help_text='key1,value1;key2,value2;', verbose_name='query数据'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='headers',
            field=models.TextField(blank=True, default='', help_text='请求头：key1,value1;key2,value2;', verbose_name='请求头'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='input_data',
            field=models.TextField(blank=True, default='', help_text='输入数据', verbose_name='输入数据'),
        ),
        migrations.CreateModel(
            name='InterfaceSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='接口名称', max_length=255, verbose_name='接口名称')),
                ('description', models.TextField(blank=True, help_text='描述', verbose_name='描述')),
                ('project', models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='api.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '接口集',
                'verbose_name_plural': '接口集',
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='数据库名称', max_length=20, verbose_name='数据库名称')),
                ('address', models.CharField(help_text='数据库地址', max_length=50, verbose_name='数据库地址')),
                ('port', models.CharField(help_text='端口', max_length=10, verbose_name='端口')),
                ('user', models.CharField(help_text='用户名', max_length=20, verbose_name='用户名')),
                ('password', models.CharField(help_text='密码', max_length=50, verbose_name='密码')),
                ('environment', models.ForeignKey(help_text='所属环境变量', on_delete=django.db.models.deletion.CASCADE, to='api.Environment', verbose_name='所属环境变量')),
            ],
            options={
                'verbose_name': '数据库',
                'verbose_name_plural': '数据库',
            },
        ),
        migrations.AddField(
            model_name='interface',
            name='interface_suite',
            field=models.ForeignKey(default=1, help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='api.InterfaceSuite', verbose_name='所属项目'),
        ),
    ]
