# Generated by Django 4.1.7 on 2023-08-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_assertion_actual_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='test_data',
            field=models.CharField(blank=True, help_text='测试数据文件名', max_length=50, null=None, verbose_name='测试数据文件名'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='case_file_name',
            field=models.CharField(blank=True, help_text='用例文件名', max_length=50, null=None, verbose_name='用例文件名'),
        ),
    ]
